### ISSUE TITLE
Update do version 3 of signature-pad

### ISSUE THREAD

**Issue by ilbonte** [neighborhood999/vue-signature-pad#119]
Hi, do you plan to update to signature pad version 3? https://github.com/szimek/signature_pad/releases

**Comment by neighborhood999** [comment]
Currently is v3 beta, I think to wait for the stable version.

**Comment by ilbonte** [comment]
signature pad has been in beta 3 for almost a year and also is default version when downloading it from npm

![image](https://user-images.githubusercontent.com/7412876/61289331-6407ab00-a7c9-11e9-8220-6a74b9955a8c.png)

**Comment by neighborhood999** [comment]
Looks good! I will upgrade and test. Thanks for your suggestion.

**Comment by ilbonte** [comment]
thanks!
