### ISSUE TITLE
v1.1.11 breaks IE 11

### ISSUE THREAD

**Issue by jvarugh** [neighborhood999/vue-signature-pad#122]
Version 1.1.11 breaks in IE 11. My VueJS app loads a blank page, no errors/warning in the console. 

Rolled back to 1.1.10 and it works. 

I wonder if this has anything to do with the update to v3 of https://github.com/szimek/signature_pad/issues/156

**Comment by shakeelosmani** [comment]
I can confirm this too. Is it linked to the other issue opened by @ostandrei ? he also reports a solution. Is there a time line for this? Do I need yo move back to 1.1.10?

**Comment by neighborhood999** [comment]
@jvarugh @shakeelosmani The problem seems to upgrade signature to v3, if want to use on IE11, downgrade to 1.10. Because of the current version just upgrade signature and not any change.
