### ISSUE TITLE
IE11 Syntaxerror

### ISSUE THREAD

**Issue by ostandrei** [neighborhood999/vue-signature-pad#126]
Hi,
Using v. 1.1.9-beta.1 of vue-signature-pad, which imports signature_pad v. 3.0.0-beta.3.

It's working well in all Browsers, but on IE11 the website can not be loaded due to an error.
The same error was reported for szimek/signature_pad here:
https://github.com/szimek/signature_pad/issues/405

The solution is to import it like this:

change from:
import SignaturePad from 'signature_pad';
to:
import * as SignaturePad from 'signature_pad/dist/signature_pad';

Can you please confirm?

**Comment by neighborhood999** [comment]
@ostandrei Thank you provide some information about this issue. I will take look.

**Comment by tskimmett** [comment]
If you're using webpack for your project that uses `vue-signature-pad`, you can add an alias in webpack config like so to fix the issue:

```
resolve: {
   alias: {
      signature_pad: 'signature_pad/dist/signature_pad.js',
   }
}
```

**Comment by gitge** [comment]
This worked for me with webpack:

```
module.exports = {
  resolve: {
    alias: {
      'signature_pad': 'signature_pad/dist/signature_pad' // <- hier without '.js' at the end!
    }
  }
};
```

And with Laravel-Mix:

```
mix.webpackConfig({
    resolve: {
        alias: {
            'signature_pad': 'signature_pad/dist/signature_pad',
        }
    }
});
```
