### ISSUE TITLE
FromDataUrl Callback

### ISSUE THREAD

**Issue by Apostlerus** [neighborhood999/vue-signature-pad#169]
Hi guys, you did a great job, thank you! But I need a callback after fromDataUrl when an image is loaded or failed. As far as I see in szimek/signature_pad it was:
```
  public fromDataURL(
    dataUrl: string,
    options: { ratio?: number; width?: number; height?: number } = {},
    callback?: (error?: ErrorEvent) => void,
  ):
```
but you guys removed it. So what can I do in this case? Except hacking such as setTimeout etc? Any advice is appriciated. Thanks!

**Comment by neighborhood999** [comment]
I add more args for `formDataURL`, trying latest version.
