### ISSUE TITLE
signaturePad's canvas collapses when using along with vuetify's tooltip

### ISSUE THREAD

**Issue by thadeuszlay** [neighborhood999/vue-signature-pad#187]
Why has the signaturePad's canvas the dimension 0 (0 width and 0 height) when using inside vuetify's tooltip (https://vuetifyjs.com/en/components/tooltips#tooltips)?

I'm using it something like this:

```
    <template v-slot:activator="{ on }">
      <span v-on="on">
        <VSignaturePad />
      </span>
    </template>
```

**Comment by neighborhood999** [comment]
Hi @thadeuszlay, you can reference #62, #117, #99 issues, I think is the same problem.
