### ISSUE TITLE
When saveType is set to 'image/jpeg' the result is black image.

### ISSUE THREAD

**Issue by gentritmustafaa** [neighborhood999/vue-signature-pad#212]
When I change the saveType to 'image/jpeg' the base64 result is wrong, which when I try to convert to real image it is showing black image.

Link to reproduce: https://codesandbox.io/s/vue-signature-pad-demo-lf5o9
You can get the value from console and paste here: https://onlinejpgtools.com/convert-jpg-to-base64

**Comment by neighborhood999** [comment]
The main reason is the default background is transparent and jpeg not support transparent background, you can check on [this line](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts#L93).

**Comment by neighborhood999** [comment]
If have any question feel free re-open.
