### ISSUE TITLE
Broken after last update

### ISSUE THREAD

**Issue by rtarling** [neighborhood999/vue-signature-pad#248]
Hi

Since the last update (3 days ago), I now see.

"[Vue warn]: Failed to mount component: template or render function not defined."

Can you please tell me how to fix it.

Kind Regards
Roland

**Comment by neighborhood999** [comment]
> Hi
> 
> Since the last update (3 days ago), I now see.
> 
> "[Vue warn]: Failed to mount component: template or render function not defined."
> 
> Can you please tell me how to fix it.
> 
> Kind Regards
> Roland

Hi @rtarling, sorry about that, I will check this error and fix it.

**Comment by rtarling** [comment]
Thanks - appreciate your help.

**Comment by neighborhood999** [comment]
> Thanks - appreciate your help.

Can you provide more information for me? e.g. your vue version or how did you use this library.

**Comment by rtarling** [comment]
Hi

I am wrapping it inside my component called "QuestionSignatureEntry".  Below I have ripped out all my code and just left the bare bones.

If I look in package.json I see the following dependencies:

"signature_pad": "^3.0.0-beta.3",
 "vue-signature-pad": "^2.0.2",

As I am using it only in this component, I have not added it to main.js (import and use).

Hope this helps.

<template>
  <div id="app">
    <div class="container">
      <div class="row">
        <div class="col-12 mt-2">
          <VueSignaturePad            
            width="100%"
            height="200px"
            ref="signaturePad"
            :options="options"
          />
        </div>
      </div>
      <div class="row">
        <div class="col-3 mt-2">
          <v-btn
            color="primary"
            class="btn btn-outline-secondary"
            @click="clear()"
          >
            Clear
          </v-btn>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import VueSignaturePad from "vue-signature-pad";
export default {
  name: "QuestionSignatureEntry",
  props: {
  },
  data: () => ({
    options: {
      penColor: "blue"
    }
  }),
  components: {
    VueSignaturePad
  },
  methods: {
    clear() {
      this.$refs.signaturePad.clearSignature();
    }
  }
};
</script>

<style>
#signature {
  border: double 3px transparent;
  border-radius: 5px;
  background-image: linear-gradient(white, white),
    radial-gradient(circle at top left, blue, blue);
  background-origin: border-box;
  background-clip: content-box, border-box;
}
</style>

**Comment by neighborhood999** [comment]
How did you bundle your app? by webpack?

**Comment by rtarling** [comment]
Yes I use webpack and the vue-cli-service

Sorry I am still relatively new to Vuejs development, so can you give me a little help to work out what is wrong.  Where do I need to look to make a fix?

**Comment by rtarling** [comment]
I use the vue ui to add plugins/dependencies, but also npm direct.  I can't remember how I added the signature component.

**Comment by neighborhood999** [comment]
You can import `VueSignature` from `main.js` and `use` keyword to use the signature component.

```js
import Vue from 'vue';
import VueSignaturePad from 'vue-signature-pad';

Vue.use(VueSignaturePad);
```

and then you can use `<VueSignature>` component in your wrapped component without `import VueSignaturePad from 'vue-signature-pad';`, you can reference [demo](https://codesandbox.io/s/n5qjp3oqv4).

**Comment by rtarling** [comment]
Fixed.  Many thanks for this.  Enjoy the rest of the weekend.
