### ISSUE TITLE
Lag or bad performance on iOS or mobile?

### ISSUE THREAD

**Issue by LaravDev** [neighborhood999/vue-signature-pad#251]
On iOS (and i assume that on android also), there is some kind of lag or bad performance, if you try to draw your signature fast, it won't work, you draw nothing on the second touch, it happens when you doit fast, i have tried with szimek/signature_pad and works with no lag at all, you can test this behavior by drawing dots fastly. 

Thanks in advance for this wrapper!

**Comment by neighborhood999** [comment]
I trying [exmaple](https://n5qjp3oqv4.codesandbox.io/) and test on my iPhone(XS), not meet this problem..., can you try to downgrade to lower version and test it?

**Comment by LaravDev** [comment]
I tried with your link on my iPhone XS Max, and still the same, it happens when you draw really fast, if you try with dots, you'll see that for example if you tap 4 times you'll see 3 dots, or 2 in some cases, but not four.

**Comment by neighborhood999** [comment]
Not sure what's going on in here, it's weird. Because this library just wrapped signature pad without more change. Can you record this problem? I trying from your description and it look works well.

**Comment by LaravDev** [comment]
My fault, still don't know what was causing the issue, but i just use it in a fresh vue installation, and worked great, sorry!
