### ISSUE TITLE
Loading signature pad in a component no longer works.  

### ISSUE THREAD

**Issue by ggGoblin** [neighborhood999/vue-signature-pad#254]
Loading signature pad in a component no longer works.    
```
components: {
    VueSignaturePad: () => import('vue-signature-pad')
},
```

**Comment by snjkg** [comment]
I am experiencing the same

**Comment by neighborhood999** [comment]
Sorry, I do not have any experience with the async load component, I need some time to research this.

You can trying below:

```js
import VueSignaturePad from 'vue-signature-pad';

Vue.use(VueSignaturePad);
```

**Comment by marcelomaia** [comment]
same here...

`[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueSignaturePad>
       <CapturaAssinaturaManual> at src/pages/recebedor/CapturaAssinaturaManual.vue
         <QPageContainer>
           <QLayout>
             <MainLayout> at src/layouts/MainLayout.vue
               <App> at src/App.vue
                 <Root>`

**Comment by juliomotol** [comment]
This works!

> ```js
> import VueSignaturePad from 'vue-signature-pad';
> 
> Vue.use(VueSignaturePad);
> ```

But is strongly believe that there should be a way to directly use the component from the plugin without the use of `Vue.use()`.

You should only use `Vue.use()` during the following cases:

- You want to modify the global instance.
- You want to add a global asset (component, directives, etc.).
- You want to inject some properties/methods to the Vue instance.

Also it is a bad practice to globally register a component (to some people at least).

My proposed solution is to add another export in the `index.js` and expose the component it self.

```js
import {vueSignatureComponent} from 'vue-signature-pad';

export default {
    components: {
        vueSignatureComponent
    }
}
```

Also, I don't know why I'm experiencing this problem just now, months ago during working with this package, I was able to locally register the component. And just recently, one of my coworkers told me that this is broken in our project.

Looking through the release and commit history, it was broken in v2.0.1 in the commit https://github.com/neighborhood999/vue-signature-pad/commit/297b64fce514e2d5a00df9a0ff7f86341b35108a.

So in v2.0.0 we were able to locally register the component. But when 2.0.1 was released, we can no longer do that.

**Comment by KAi2020RM** [comment]
Same problem here with v2.0.2. 

Is a solution already being in progress or is there a workaround to register the component it locally?

**Comment by juliomotol** [comment]
> Same problem here with v2.0.2.
> 
> Is a solution already being in progress or is there a workaround to register the component it locally?

I guess for the meantime we could do something like this:

```js
import VueSignaturePad from 'vue-signature-pad/src/components/VueSignaturePad.vue';

export default {
    components: {
        VueSignaturePad
    },
}
```

I haven't tested this yet, but the idea is to point directly to the SFC of the `VueSignaturePad`.

**Comment by mort3za** [comment]
> ```js
> src/components/VueSignaturePad.
> ```

There is no src folder in node_modules/vue-signature-pad. Seems it's not possible right now.

**Comment by tarik23** [comment]
+1 Have the same problem. I don't use async. But still no luck

**Comment by ReynerHL** [comment]
First, thanks so much for your package and your time @neighborhood999.

Something went wrong since 2.0.1 version. We can use the package through global registration (Vue.use at entry point), but in Single File Components it not longer work.

Until a fix arrive, we can use version 2.0.0.
`npm remove vue-signature-pad && npm install vue-signature-pad@2.0.0`

Be sure that the entry in the package.json remains as follow:
`"vue-signature-pad": "2.0.0",`

Hope this temporal workaround helps someone.

**Comment by neighborhood999** [comment]
Hi guys, sorry about the issue. I'm a long time didn't write vue.js, so I decide to revert 297b4f change.

**Comment by danbars** [comment]
Hi @neighborhood999, did you commit this revert? `2.0.2` which is the latest still doesn't work.

**Comment by lucasmichel** [comment]
> First, thanks so much for your package and your time @neighborhood999.
> 
> Something went wrong since 2.0.1 version. We can use the package through global registration (Vue.use at entry point), but in Single File Components it not longer work.
> 
> Until a fix arrive, we can use version 2.0.0.
> `npm remove vue-signature-pad && npm install vue-signature-pad@2.0.0`
> 
> Be sure that the entry in the package.json remains as follow:
> `"vue-signature-pad": "2.0.0",`
> 
> Hope this temporal workaround helps someone.

I had the same problem and the tip above solved

**Comment by neighborhood999** [comment]
The latest experiment version `2.0.3-beta.3` trying to fix this issue, upgrade to Vue 3 with SFC component.

Now you can import component by this way:

```vue
<script>
import { VueSignaturePad } from 'vue-signature-pad';

export default {
  components: {
    VueSignaturePad
  }
}
</script>
```

also the `.use` still support:

```js
createApp(youApp).use(VueSignaturePad)
```

You can try this by installing the experiment version:

```sh
$ yarn add vue-signature-pad@2.0.3-beta.3
```

**Comment by neighborhood999** [comment]
Please try the latest 2.0.3 version.

**Comment by neighborhood999** [comment]
Release `2.0.4` for vue 2, the original `2.0.3` version will be deprecated.

Vue3 support will release in `3.x.x` version.

**Comment by zhangyunliang** [comment]
only this can work **npm remove vue-signature-pad && npm install vue-signature-pad@2.0.0**
