### ISSUE TITLE
HOW TO QUESTION: How to add a white background to the signature.

### ISSUE THREAD

**Issue by LaravDev** [neighborhood999/vue-signature-pad#273]
Hi!, thanks a lot for this wrapper, it has been really helpful, i'm just wondering if there is a way to set a background color to the image produced with the pad, when i save the signature, it comes in PNG so the background is transparent and it won't be readable as is, is there a way to add a white background to the resulted image? thanks in advance for any help or hint.

**Comment by cepm-nate** [comment]
Did you look at the options for the parent project? https://github.com/szimek/signature_pad

**Comment by LaravDev** [comment]
You are right, sorry for the question, I did it already.
