### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by tng10** [neighborhood999/vue-signature-pad#292]
First of all thanks @neighborhood999 for bringing this package into Vue2 ecosystem. 

With the recent release of Vue3 many packages started upgrading their versions and I would like to share with you all a Vue3 version of this `signature pad` component. 

https://github.com/tng10/vue3-signature-pad

#238

**Comment by bilalswiftsolutions** [comment]
@tng10  documentation of your package is not understandable i am unable to use that package

**Comment by andreiradoi** [comment]
> @tng10 documentation of your package is not understandable i am unable to use that package

You can use the documentation from this package and for the vue3 one just use SignaturePad instead of VueSignaturePad

**Comment by neighborhood999** [comment]
Next release version will upgrade to v3.

**Comment by bci24** [comment]
> @andreiradoi You can use the documentation from this package and for the vue3 one just use SignaturePad instead of VueSignaturePad

Is not working. I can't make it work in vue 3. What ever I try:

`TypeError: app.component is not a function`

**Comment by andreiradoi** [comment]
@bci24 I don't think your issue is related to this package. I'd wager that you'll get the same error when trying to call any function defined in App Component.

**Comment by JBtje** [comment]
> > @andreiradoi You can use the documentation from this package and for the vue3 one just use SignaturePad instead of VueSignaturePad
> 
> Is not working. I can't make it work in vue 3. What ever I try:
> 
> `TypeError: app.component is not a function`

My guess is you did this? (which won't work)
```
import VueSignaturePad from 'vue-signature-pad';

export default {
    components: {
        VueSignaturePad,
    },
    ...
```

You need to register the package correctly using:
```
import Vue from 'vue';
import VueSignaturePad from 'vue-signature-pad';

Vue.use(VueSignaturePad);
```
