### ISSUE TITLE
Unknown custom element: <vuesignaturepad> 

### ISSUE THREAD

**Issue by thamibn** [neighborhood999/vue-signature-pad#309]
Unknown custom element: <vuesignaturepad> - did you register the component correctly? For recursive components, make sure to provide the "name" option

//app.js
import VueSignaturePad from 'vue-signature-pad';
Vue.use(VueSignaturePad);

//i have used it like this as per the demo
<VueSignaturePad width="500px" height="500px" ref="signaturePad" />

//package.json
"vue": "^2.1.10",
"vue-signature-pad": "^2.0.2",

i have also tried the below version
"vue-signature-pad": "^2.0.0",

**Comment by neighborhood999** [comment]
In the `<template>`, did you use `<VueSignaturePad` or `<vuesignaturepad`?

**Comment by thamibn** [comment]
> In the `<template>`, did you use `<VueSignaturePad>` or `<vuesignaturepad>`?

I have used
```
<VueSignaturePad width="500px" height="500px" ref="signaturePad" />

```

just like in demo.

i even tried to reqister it global like below
```
import  VueSignaturePad from 'vue-signature-pad';
Vue.component('VueSignaturePad', VueSignaturePad)
```

**Comment by neighborhood999** [comment]
No idea what's going on, because the component has a name:

https://github.com/neighborhood999/vue-signature-pad/blob/39355ef31de99f2c76189110f61db5dd91b3fbfe/src/components/VueSignaturePad.vue#L13

I will publish the next version to fix the register & import component issues, before publish you can try the beta version, see the [comment](https://github.com/neighborhood999/vue-signature-pad/issues/254#issuecomment-877590660).

**Comment by thamibn** [comment]
> No idea what's going on, because the component has a name:
> 
> https://github.com/neighborhood999/vue-signature-pad/blob/39355ef31de99f2c76189110f61db5dd91b3fbfe/src/components/VueSignaturePad.vue#L13
> 
> I will publish the next version to fix the register & import component issues, before publish you can try the beta version, see the [comment](https://github.com/neighborhood999/vue-signature-pad/issues/254#issuecomment-877590660).

The Beta unfotunately requires Vue3, it doesnt work on Vue2.

Yes please have a look at it, and make it eay to import the compent local.

**Comment by neighborhood999** [comment]
> > No idea what's going on, because the component has a name:
> > https://github.com/neighborhood999/vue-signature-pad/blob/39355ef31de99f2c76189110f61db5dd91b3fbfe/src/components/VueSignaturePad.vue#L13
> > 
> > I will publish the next version to fix the register & import component issues, before publish you can try the beta version, see the [comment](https://github.com/neighborhood999/vue-signature-pad/issues/254#issuecomment-877590660).
> 
> The Beta unfotunately requires Vue3, it doesnt work on Vue2.
> 
> Yes please have a look at it, and make it eay to import the compent local.

Can you reproduce your issue on the codesandbox? I think the problem probably is your vue version is too lower, can you try to upgrade your vue to `2.6.4` and try again?

The [example](https://codesandbox.io/s/n5qjp3oqv4) works fine, so just my guess.

**Comment by neighborhood999** [comment]
Close, Feel free to reopen the issue.

**Comment by neighborhood999** [comment]
Release `2.0.4` for vue 2, the original 2.0.3 version will be deprecated.

**Comment by thamibn** [comment]
> Release `2.0.4` for vue 2, the original 2.0.3 version will be deprecated.

It is working prefectly now thank you very much.

1.Updated my laravel-mix to version 6.
2.Updated my Vue version to the one you suggested.
3.```components: {
        'vue-signature-pad': VueSignaturePad
    },
    ```
    
    When i was defining it under componets i name it in kebab-case.
    
    works like a charm!!!
