### ISSUE TITLE
Release 0.1.0 broke HMR

### ISSUE THREAD

**Issue by eidellev** [neighborhood999/vue-signature-pad#32]
Hi @neighborhood999 and thank you for this plugin. 
There is a small issue I encountered in release `0.1.0`: after upgrading, HMR stopped working for me. I downgraded to `0.0.96` and it started working again.

I use Nuxt `1.4.0` in my project. 
Thanks!

**Comment by neighborhood999** [comment]
Hi @eidellev! Did you have try to reinstall `node_modules`?
