### ISSUE TITLE
Event listeners are not removed when unmounting the component in Vue 3

### ISSUE THREAD

**Issue by ropez** [neighborhood999/vue-signature-pad#328]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-signature-pad@3.0.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-signature-pad/dist/vue-signature-pad.esm.js b/node_modules/vue-signature-pad/dist/vue-signature-pad.esm.js
index eda9d37..dea6403 100644
--- a/node_modules/vue-signature-pad/dist/vue-signature-pad.esm.js
+++ b/node_modules/vue-signature-pad/dist/vue-signature-pad.esm.js
@@ -90,7 +90,7 @@ var script = defineComponent({
     this.resizeCanvas();
   },
 
-  beforeDestroy() {
+  beforeUnmount() {
     if (this.onResizeHandler) {
       window.removeEventListener('resize', this.onResizeHandler, false);
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by neighborhood999** [comment]
> ```diff
> beforeDestroy
> ```

Hi @ropez!

Thanks for reminding me. After upgrade to vue3, I did not notice the latest API is breaking change.

I will fix it, but PRs are welcome!

ref: https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes

**Comment by neighborhood999** [comment]
Hi @ropez!

Thanks for reminding me. After upgrade to vue3, I did not notice the latest API is breaking change.

I will fix it, but PRs are welcome!

ref: https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes

**Comment by neighborhood999** [comment]
Hi @ropez!

Thanks for reminding me. After upgrade to vue3, I did not notice the latest API is breaking change, I will fix it, but PRs are welcome!

ref: https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes
