### ISSUE TITLE
Screen rotating clear signature

### ISSUE THREAD

**Issue by madeITBelgium** [neighborhood999/vue-signature-pad#34]
When you rotate a device (or the window is resized), the canvas is cleared. Also on iPhone when you scroll, the signature is also cleared.

**Comment by neighborhood999** [comment]
Why clear canvas you can reference [here](https://github.com/szimek/signature_pad#tips-and-tricks).

On mobile scroll scenario, I will check this problem.

**Comment by madeITBelgium** [comment]
> This clearing of the canvas by the browser can be annoying, especially on mobile devices e.g. when screen orientation is changed. There are a few workarounds though, e.g. you can lock screen orientation, or read an image from the canvas before resizing it and write the image back after.

I will try this. I think it is the same with scroll. https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020
