### ISSUE TITLE
Change 2.0.4 - 2.0.5

### ISSUE THREAD

**Issue by rtarling** [neighborhood999/vue-signature-pad#363]
Hi

What has changed between these versions?  I have multiple signatures (with different refs).  Now only the first one works.

Kind Regards
Roland

**Comment by neighborhood999** [comment]
Hi @rtarling, I didn't create a changelog, and sorry about that.

The changes just added a new prop to control the device pixel ratio, see #360.

**Comment by rtarling** [comment]
Hi

No problem.  I thought there was an issue but it was a coincidence.  At the same time as your upgrade I made a minor change to my usage of Vuetify’s <v-window-item> component (like a carousel), setting it to “eager” – effectively pre-loading the content off-screen.  This screws up the signature component – I think because when it creates the canvas it has the wrong dimensions, so when I write it is rendering somewhere off-screen.

Is there any way to force the control to recalculate the canvas and its scaling?  Have you seen this issue before?

I would really appreciate any ideas you might have as I am a bit stuck.

Kind Regards
Roland
