### ISSUE TITLE
No method for converting base64 image to image

### ISSUE THREAD

**Issue by tryuenyalung** [neighborhood999/vue-signature-pad#43]
// Draws signature image from data URL.
// NOTE: This method does not populate internal data structure that represents drawn signature. Thus, after using #fromDataURL, #toData won't work properly.
signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");

**Comment by neighborhood999** [comment]
Can you provide code to reproduce your problem?

**Comment by tryuenyalung** [comment]
nvm, i just made a function, great work btw keep it up ! 👍 

https://gist.github.com/tryuenyalung/1b3eb074634ac6461f9611f81611dfc1
