### ISSUE TITLE
Signature Pad Doesn't Appear on Default Resolution

### ISSUE THREAD

**Issue by deanilvincent** [neighborhood999/vue-signature-pad#54]
Good day,

First of all, I'd like to thank you for this helpful package. Now, I can freely use this on my vue.js project.

By the way, It's my first time using this package today and unfortunately, I'm facing a bug or an issue.

The problem appears during the default resolution of the page and signature pad doesn't appear properly. But when I resize the window, then the signature appears properly.

Here's the gif screen clip the I've created:
![Alt Text](https://i.imgur.com/xIzcSQC.gif)

Here are my codes:
     `<template>
        <div>
              ...
             <VueSignaturePad width="100%"
                                     height="300px"
                                     ref="signaturePad"
                                     saveType="image/png"/>
        </div>
     </template>`

    <script>
     import Vue from 'vue';
     import VueSignaturePad from 'vue-signature-pad';

     Vue.use(VueSignaturePad);
     export default { ... }
    </script>

Thank you in advance!

**Comment by neighborhood999** [comment]
Hi @deanilvincent :

That's weird. In my case, it can work normally. Can you try to on [signature_pad](https://github.com/szimek/signature_pad) 's demo?

**Comment by deanilvincent** [comment]
I just used the original one.

**Comment by traic** [comment]
Isolated the issue down to these two lines causing the canvas to become zero in width and height:

var canvas = document.getElementById('signature-pad')

    // Adjust canvas coordinate space taking into account pixel ratio,
    // to make it look crisp on mobile devices.
    // This also causes canvas to be cleared.
    function resizeCanvas() {
        // When zoomed out to less than 100%, for some very strange reason,
        // some browsers report devicePixelRatio as less than 1
        // and only part of the canvas is cleared then.
        var ratio =  Math.max(window.devicePixelRatio || 1, 1)
        canvas.width = canvas.offsetWidth * ratio
        canvas.height = canvas.offsetHeight * ratio
        canvas.getContext("2d").scale(ratio, ratio)
    }

    //window.onresize = resizeCanvas
    //resizeCanvas()

Just comment them out...

**Comment by louisaoge** [comment]
This worked for me 
`<VueSignaturePad :options="{onBegin: () => {$refs.signaturePad.resizeCanvas()}}" ref="signaturePad"/>`
