### ISSUE TITLE
TypeScript support (.d.ts)

### ISSUE THREAD

**Issue by Cross77** [neighborhood999/vue-signature-pad#61]
Hi,
thank you for the best and hassle-free signature system in the vue but do you support TypeScript? I can not find any files with the extension .d.ts or @types/vue-signature-pad package.
![image](https://user-images.githubusercontent.com/11912763/43208780-76c2d7d0-902b-11e8-934d-bb2ab244ebb4.png)

Thank you for your help and best regards :)

**Comment by neighborhood999** [comment]
Hi, @Cross77 

Not currently support ts yet. I don't have any experience on TypeScript, so I need more time to learn and try, but PRs welcome. 😀

**Comment by neighborhood999** [comment]
@rojobo Cool! I will try this.

**Comment by neighborhood999** [comment]
@rojobo Can you use [Augmenting-Types-for-Use-with-Plugins](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins) to try the defined `index.d.ts`?

**Comment by rojobo** [comment]
@neighborhood999 yes that's what that file does just put it under an index.d.tx file and it will work when you install. I can do a pull request if you want
Im using it in production

**Comment by neighborhood999** [comment]
@rojobo Cool! I'm not familiar typescript and defined for Vue library, feel free to create the pull request, thank you.
