### ISSUE TITLE
VueSignaturePad not display properly until browser resize

### ISSUE THREAD

**Issue by TheRagingLoser** [neighborhood999/vue-signature-pad#62]
Hi, I am clearly doing something wrong but when I view the page with the signature pad on it all I get is the border until I manually resize the browser window, then the signature pad appear along with anything that may have been scribbled onto the blank space. Below is the code:
```
<template>
    <v-container fluid grid-list-md>
        <div class="display-1">Create a new order</div>
        <v-dialog v-model="dialog" fullscreen hide-overlay transition="dialog-bottom-transition">
          <v-btn slot="activator" color="primary" dark>Sign For Order</v-btn>
          <v-card height="100%">
            <v-toolbar dark color="primary">
              <v-toolbar-title>Sign Below</v-toolbar-title>
              <v-btn icon dark @click="dialog = !dialog"></v-btn>
            </v-toolbar>

            <VueSignaturePad
              width="95%"
              height="80%"
              ref="signaturePad"
              :options="sigopt"
              :customStyle="sigStyle"
            />

            <v-btn @click="clear">Clear</v-btn>
            <v-btn @click="save">Finalize Order</v-btn>
          </v-card>
        </v-dialog>
    </v-container>
</template>

<script>
import VueSignaturePad from 'vue-signature-pad'

export default {
  created() {
  },
  data() {
    return {
      sigopt: {
        backgroundColor: 'rgb(250,235,215)',
        minWidth: 2.0,
      },
      sigStyle: { 
        border: '1px black solid',
      },
      dialog: false,
    }
  },
  methods: {
    clear() {
    },
    save() {
      this.dialog = false
    },
  },
  components: {
    VueSignaturePad
  }
}
</script>
```
Sorry if this isn't the place to ask this but,=, is it my code or a bug of some kind. Kindly appreciate any help. Thanks.

**Comment by neighborhood999** [comment]
@TheRagingLoser can you reproduce this problem on [CodeSanxbox](https://codesandbox.io/)? In #54 had a similar problem, but I can't reproduce.

**Comment by TheRagingLoser** [comment]
@neighborhood999 Thanks for your quick response. It seems identical to the issue in #54. I have tried in CodeSandbox and it seemed to work fine. I'm thinking it may have something to do with the Vuetify dialog box I am placing it in. I will do some test with it on the page without the dialog box. P.S. thanks for the great work on this compoinent.

**Comment by scp-nm** [comment]
An interesting thing I've noticed (I'm also using Vuetify's framework) is that when the component is displayed the `canvas` `width` and `height` are both `0`, after the browser resize these attributes then have values.
Before resizing browser:
![image](https://user-images.githubusercontent.com/32037777/45683518-da9d3300-bb3b-11e8-89e0-532b604c5e43.png)
After resizing browser window:
![image](https://user-images.githubusercontent.com/32037777/45683571-f4d71100-bb3b-11e8-8bb0-61fe21628eb4.png)

Did you manage to solve this @TheRagingLoser ?

**Comment by scp-nm** [comment]
More info (found on Vuetify's discord 'need-help' channel):

> toki - 17/04/2018
> Because the signature pad uses touch events, it may not work properly under scrollable element (like v-app). 
> So I just put it into a full screen v-dialog, set scrollable = false and hope it work well.
> 
> But it still can't get any touch event unless 
> 
> * resize the window manually (not suitable for mobile usage)
> * try to scroll (yes, it can still scroll with v-dialog + scrollable = false)
> 
> Is there a way I could completely turn off scroll on v-dialog or there's other component is suitable for this job?

So I'm going to test some ideas out - if I get something working I'll update this so that it can hopefully help others in the future.

**Comment by traic** [comment]
Isolated the issue down to these two lines causing the canvas to become zero in width and height:

var canvas = document.getElementById('signature-pad')

    // Adjust canvas coordinate space taking into account pixel ratio,
    // to make it look crisp on mobile devices.
    // This also causes canvas to be cleared.
    function resizeCanvas() {
        // When zoomed out to less than 100%, for some very strange reason,
        // some browsers report devicePixelRatio as less than 1
        // and only part of the canvas is cleared then.
        var ratio =  Math.max(window.devicePixelRatio || 1, 1)
        canvas.width = canvas.offsetWidth * ratio
        canvas.height = canvas.offsetHeight * ratio
        canvas.getContext("2d").scale(ratio, ratio)
    }

    //window.onresize = resizeCanvas
    //resizeCanvas()

Just comment them out...

**Comment by scp-nm** [comment]
@traic - thanks for the info. I did however manage to get it working without needing a custom version.

The signature pad is being used in a navigation drawer, and was being called when the navigation drawer was displayed. However, the navigation drawer also contains Vuetify's `v-stepper` component, so what I've done is only set the signature pad to display if the `v-stepper-step` is the showing containing the signature pad.

This is working like a dream!

**Comment by dark-matter-matters** [comment]
I can confirm @Leemanbok 's solution worked for me. I placed it within my display property (used with v-show) on the watch section. Placing it on the mounted section does not work. 

```
watch: {
            display: function(value){
                this.displayDialog = value;
                this.$nextTick(function () {
                    this.$refs.signaturePad.resizeCanvas();
                    this.$refs.signaturePad.fromDataURL(this.editedItem._signature);
                }
           };
        },
```

**Comment by camoore** [comment]
I ran into this same issue and the best solution I found was `<VueSignaturePad :options="{onBegin: () => {$refs.signaturePad.resizeCanvas()}}"  ref="signaturePad"/>`

**Comment by MichiWoo** [comment]
I solved it, adding in the mounted.
<template lang="pug">
      VueSignaturePad#signature(
          width="250px"
          height="250px"
          ref="signaturePad"
          :options="options"
          v-show="isShow"
        )
</template>
data() {
      return {
        options: {
          penColor: "#c0f"
        },
        isShow: false
      }
    },
methods : {
   iniciarcomponente() {
        this.showWithResize()
    },
   showWithResize() {
        this.isShow = true
        this.$refs.signaturePad.$refs.signaturePadCanvas.width = 250
        this.$refs.signaturePad.$refs.signaturePadCanvas.height = 250
      },
},
mounted () {
         this.initcomponent()
},

**Comment by spanner28** [comment]
I do this, works if you set the signaturePad width to a percentage like 100%
```javascript
mounted() {
      var sig = this.$refs.signaturePad.$el
      sig.querySelector('canvas').setAttribute('width', sig.offsetWidth)
      sig.querySelector('canvas').setAttribute('height', sig.offsetHeight)
}
```

**Comment by quroom** [comment]
If you are using v-dialog in vuetify, you need to use eager prop in your dialog.
The problem is when your vue-signature-pad is loaded, v-dialog size was not fixed.
So v-dialog set width and height zero.
For fixing this problem, I spent around 2hours holly..
I hope other people do not waste of time like me

**Comment by marknuyens** [comment]
> I ran into this same issue and the best solution I found was to call the resizeCanvas in the onBegin function
> 
> `<VueSignaturePad :options="{onBegin: () => {$refs.signaturePad.resizeCanvas()}}" ref="signaturePad"/>`

This appears to work for the situation where you would like to start drawing. However, if you've already provided data and wish to regenerate it, then you'll run into the same rendering issue. I've been able to solve this using the following workaround:

```js
// don't forget to set the data using:
// this.$refs.signaturePad.fromData(...);
// set a timeout of 0ms to force a render
setTimeout(() => this.$refs.signaturePad.resizeCanvas(), 0);
```
By setting the timer on `0`, you'll notice no delay, but it will force the pad to render the signature.

**Comment by Orange-Men** [comment]
@marknuyens 
> This appears to work for the situation where you would like to start drawing. However, if you've already provided data and wish to regenerate it, then you'll run into the same rendering issue.

I faced the same problem, but in my case I was using .fromDataURL( to set the “initial” signature.
I fixed this by rewriting the resizeHandler( method:

```js
     <VueSignaturePad
        :ref="refName"
        class="vue-signature-pad"
        :width="width"
        :height="height"
        :options="{
          throttle: 8,
          onBegin,
          onEnd,
          resizeHandler
        }"
      />

...

    methods: {
        resizeHandler() {
            let ref = this.$refs[this.refName];

            const canvas = ref.$refs.signaturePadCanvas;
            const data = ref.signaturePad.toData();
            const ratio = ref.scaleToDevicePixelRatio
                ? Math.max(window.devicePixelRatio || 1, 1)
                : 1;

            canvas.width = canvas.offsetWidth * ratio;
            canvas.height = canvas.offsetHeight * ratio;
            canvas.getContext('2d').scale(ratio, ratio);

            ref.signaturePad.clear();
            ref.signatureData = ref.TRANSPARENT_PNG;

            if (data.length) {
                ref.signaturePad.fromData(data);
            } else {
                // hack, cause original resizeHandler doesn't work
                ref.fromDataURL(this.form.signature);
            }
        },
```

signaturePad.toData() - always returns an empty array

Anyone have any ideas on how to fix this so I don't have to do smells code?

**Comment by Orange-Men** [comment]
https://github.com/szimek/signature_pad?tab=readme-ov-file#api

```js
// NOTE: This method does not populate internal data structure that represents drawn signature. Thus, after using #fromDataURL, #toData won't work properly.
signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");
```

> **Thus, after using #fromDataURL, #toData won't work properly.**

Oh... nevermind)
