### ISSUE TITLE
Error when using options

### ISSUE THREAD

**Issue by kaptk2** [neighborhood999/vue-signature-pad#97]
When trying to use the options as outlined in the README file and the following error shows in the console:
[Vue warn]: Invalid prop: type check failed for prop "options". Expected Object, got String with value "{ onBegin, onEnd }".

Here is my how I added the options, following what was outlined in the readme file.
<VueSignaturePad
    id="signature"
   width="100%"
   height="500px"
   ref="signaturePad"
   options="{ onBegin, onEnd }"
/>

Here is a code sandbox link showing the issue: https://codesandbox.io/s/n5qjp3oqv4

**Comment by neighborhood999** [comment]
`{ onBegin, onEnd }` is shorthand, make sure your methods have `onBegin()` or `onEnd()`, I didn't see the `onBegin` or `onEnd` method in your code.

**Comment by neighborhood999** [comment]
Sorry for the wrong example in README, I loss `:` operator, here is the example: https://codesandbox.io/s/rm1vk8wn1n

**Comment by kaptk2** [comment]
Thank you for the example, that was the exact issue now everything works as expected.
